### ISSUE TITLE
Configure CI NUC

### ISSUE THREAD

**Issue by bunnie** [betrusted-io/betrusted-soc#16]
once the hardware is in, I'm going to need help configuring this correctly with the right scripts, hooks and security ...

**Comment by tmarble** [comment]
Can we do this on Debian stable -or- must we use Windows?

**Comment by bunnie** [comment]
I use the toolchain with Ubuntu, but it stands to reason it may work with Debian as well. I consider the two basically interchangeable from a tooling standpoint.

**Comment by bunnie** [comment]
If you get a NUC up and running from your side before we do, please keep a log of the configuration so we can duplicate it here.

**Comment by bunnie** [comment]
done
