### ISSUE TITLE
WDT: Add Watchdog Timer

### ISSUE THREAD

**Issue by xobs** [betrusted-io/betrusted-soc#19]
It would be good to have the system reboot itself if it locks up, or if something goes really wrong.

**Comment by bunnie** [comment]
Note to self -- provide an option to look at CFGMCLK from the STARTUPE2 block as an internal time reference for the WDT. This would allow the WDT to still trigger even if the external clock is stopped.

**Comment by bunnie** [comment]
WDT merged in 26a149e03aac85f0b39ccae16910a62ea0e5e2bf

The WDT for Precursor runs off of the internal ring oscillator, so that attackers cannot simply stop the external clock to defeat the WDT.
