### ISSUE TITLE
Cannot recursively clone submodules: enjoy-digital/black-parrot missing

### ISSUE THREAD

**Issue by blakesmith** [betrusted-io/betrusted-soc#28]
Hi there!

I wanted to generate the SoC with LiteX, but am getting recursive clone errors for a `enjoy-digital/black-parrot` repository:

```
git clone --recurse-submodules https://github.com/betrusted-io/betrusted-soc.git
...
Username for 'https://github.com': 
Password for 'https://github.com': 
remote: Repository not found.
fatal: Authentication failed for 'https://github.com/enjoy-digital/black-parrot.git/'
fatal: clone of 'https://github.com/enjoy-digital/black-parrot.git' into submodule path '/home/blake/src/betrusted-soc/deps/rom-locate/deps/litex/litex/soc/cores/cpu/blackparrot/pre-alpha-release' failed
Failed to clone 'litex/soc/cores/cpu/blackparrot/pre-alpha-release'. Retry scheduled
```

Can someone help resolve? Thanks! Been enjoying playing and hacking on my Precursor so far. :+1: 

EDIT: Looks like `compiler-rt` is having similar issues, though it seems to be stuck in some redirect loop:

```
Cloning into '/home/blake/src/betrusted-soc/deps/rom-locate/deps/litex/litex/soc/software/compiler_rt'...
fatal: unable to access 'https://git.llvm.org/git/compiler-rt/': Maximum (20) redirects followed
fatal: clone of 'https://git.llvm.org/git/compiler-rt' into submodule path '/home/blake/src/betrusted-soc/deps/rom-locate/deps/litex/litex/soc/software/compiler_rt' failed
Failed to clone 'litex/soc/software/compiler_rt'. Retry scheduled
```

**Comment by bunnie** [comment]
I'm having a look into this...the fix might be to just not recurse submodules and rely instead of the bootstrapper inside the betrusted_soc.py script but I need to setup an environment to test it.

**Comment by bunnie** [comment]
OK. I think I've removed the false dependency. The problem is that `rom-locate` refers to an ancient version of Litex, which had a bunch of repos be deleted. 

I just vendored in the `rom-locate` stuff, it's fairly stable and hasn't changed in years, thus removing that dependency. I just pulled a clean version and started the build, it seems to be running smoothly now.

**Comment by blakesmith** [comment]
Thanks @bunnie! The recursive clone is working great now. After the big old Vivado download, I should be able to test a full build.
